services:
  db:
    container_name: postgres-spring-boot   
    image: postgres:16.2-alpine 
    restart: always 
    environment:
      POSTGRES_DB: DB01B 
      POSTGRES_USER: hkhlifi 
      POSTGRES_PASSWORD: DBFOR01B
      TZ: Africa/Casablanca
      PGTZ: Africa/Casablanca
    ports:
      - "5332:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - app-network

  backend:
    container_name: spring-boot-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/DB01B
      SPRING_DATASOURCE_USERNAME: hkhlifi
      SPRING_DATASOURCE_PASSWORD: DBFOR01B
      FILE_UPLOAD_DIR: /app/upload
      FILE_FETCH_URL: http://localhost:8080/api/post/file/
      TZ: Africa/Casablanca
    volumes:
      - backend_uploads:/app/upload
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    container_name: angular-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data:
  backend_uploads:

networks:
  app-network:
    driver: bridge